import streamlit as st
import pandas as pd
import os
from presentation.state.session_state_manager import initialize_session_state
from domain.services.traderepublic_parser import TradeRepublicParser

st.set_page_config(page_title="Trade Republic Analysis", page_icon="📊", layout="wide")

initialize_session_state()

st.title("📊 Trade Republic Portfolio Analysis")

# File path
file_path = "data/2026-04-26-traderepublic-export.csv"

if not os.path.exists(file_path):
    st.error(f"File not found: {file_path}")
    st.stop()

# Load and parse
parser = TradeRepublicParser(file_path)
metrics = parser.get_metrics()
df = parser.df

st.header("Strategy for ROI & Performance Calculation")
st.markdown("""
To accurately calculate the Total Performance and ROI of the portfolio from the exported transactions, we need to categorize them effectively and apply the following strategy:

### 1. Transaction Categorization
- **Cash Deposits & Withdrawals**: Identified by transactions matching the account owner's name. These determine the raw cash flow into the account.
- **Investments (ETFs, Stocks, Bonds)**: Identified by "Saving executed", "Buy Order", or "Sell Order". These represent capital allocated to assets.
- **Dividends & Interest**: Identified by "Cash dividend", "Interest payment", etc. These are returns generated by the assets or uninvested cash.
- **Personal Expenses**: Any remaining negative cash flows (e.g., Japan trip expenses, UK Visas, etc.). These must be deducted from the total deposits to compute the true *Net Investable Capital*.

### 2. Calculation Strategy
- **Net Investable Capital**: `Total Deposits + Total Withdrawals - Personal Expenses`
- **Current Portfolio Value**: Requires fetching the current market price for all active assets (Stock, ETFs, Bonds) and multiplying by the accumulated quantities, plus any uninvested cash balance.
- **Total Performance (€)**: `Current Portfolio Value - Net Investable Capital`
- **ROI (%)**: `(Total Performance / Net Investable Capital) * 100`
""")

st.header("Extracted Metrics")
col1, col2, col3 = st.columns(3)

col1.metric("Total Deposits", f"€{metrics.total_deposits:,.2f}")
col1.metric("Personal Expenses", f"€{-metrics.total_expenses:,.2f}")
col1.metric("Net Investable Capital", f"€{metrics.net_investable_capital:,.2f}")

col2.metric("Total Dividends & Interest", f"€{metrics.total_dividends_interest:,.2f}")
col2.metric("Net Invested in Assets", f"€{-metrics.net_invested_in_assets:,.2f}")
col2.metric("Theoretical Cash Balance", f"€{metrics.cash_balance:,.2f}")

st.header("Categorized Transactions")
categories = df['category'].unique().tolist()
selected_category = st.selectbox("Filter by Category", ["All"] + categories)

if selected_category == "All":
    st.dataframe(df)
else:
    st.dataframe(parser.get_transactions_by_category(selected_category))
